version: 2

sources:
  - name: raw # This is the logical name for the dataset
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales # The actual table name in the database
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship
      

